<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1V9PIPH" failures="0" tests="4" name="Screens.RecentFeed" time="0.012" errors="1" timestamp="05 Sep 2018 09:17:49 GMT" skipped="3">
  <testcase classname="Screens.RecentFeed" name="setUpBeforeTest" time="0.012">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Declaration.MethodDeclaration.enterValidCredential(MethodDeclaration.java:57)
at Screens.SignInFeature.validSignIn(SignInFeature.java:111)
at Screens.RecentFeed.setUpBeforeTest(RecentFeed.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUpBeforeTest -->
  <testcase classname="Screens.RecentFeed" name="testPostStatusIntoProfile" time="0.000">
    <skipped/>
  </testcase> <!-- testPostStatusIntoProfile -->
  <testcase classname="Screens.RecentFeed" name="testValidSignIn" time="0.000">
    <skipped/>
  </testcase> <!-- testValidSignIn -->
  <testcase classname="Screens.RecentFeed" name="testInvalidSignIn" time="0.000">
    <skipped/>
  </testcase> <!-- testInvalidSignIn -->
</testsuite> <!-- Screens.RecentFeed -->
